# Generated by Django 5.0.4 on 2024-04-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_port_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='visiting',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=100),
        ),
    ]
